# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import member.models.myuser


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170924_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=24)),
            ],
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', member.models.myuser.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='emailtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
