# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20171007_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.CharField(max_length=35),
        ),
    ]
