# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20171022_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=models.CharField(blank=True, max_length=56, unique=True),
        ),
    ]
