# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_myuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='slug',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
