# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:25
from __future__ import unicode_literals

from django.db import migrations
import utils.fields.custom_image_fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20171024_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='my_photo',
            field=utils.fields.custom_image_fields.CustomImageField(max_length=255, upload_to=''),
        ),
    ]
