# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('프로그래밍언어', '언어'), ('운영체제', '운영체제'), ('자료구조/알고리즘', '자료구조/알고리즘'), ('네트워크', '네트워크'), ('데이터베이스', '데이터베이스'), ('ETC', 'etc(소프트웨어공학 등)')], max_length=50),
        ),
    ]
