# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_sellbookregister_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellbookregister',
            options={'ordering': ['-pk']},
        ),
    ]
