# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20171011_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstatus',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
