# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_bookstatus_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstatus',
            name='sell_book_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_status', to='book.SellBookRegister'),
        ),
    ]
